<!DOCTYPE html>
<html>
<head>
    <title>Реєстрація</title>
</head>
<body>
<h1>Реєстрація користувача</h1>
<form action="/register" method="post">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br><br>

    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br><br>

    <button type="submit">Зареєструватися</button>
</form>
</body>
</html>
